name: SSD1306 Display Add-on
version: "1.0"
slug: ssd1306_display
description: Display boot status on SSD1306 via I2C
startup: services
boot: auto
host_network: true
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
devices:
  - /dev/i2c-1
options: {}
schema: {}
